import { useDS } from '@/ds/DesignSystem'

/**
 * Phase 2 verification.
 *
 * Every component here is resolved through useDS(), so this single file renders
 * against whichever sandbox its frame declares. The Tailwind utilities below are
 * generated by the sandbox stylesheet — the shell's build cannot see this file.
 */
export default function ComponentProbe() {
  const { Button, Badge, Input, Tag, Spinner, Kbd } = useDS()

  return (
    <main className="min-h-dvh bg-[var(--background)] p-8 text-[var(--foreground)]">
      <h1 className="mb-1 text-lg font-semibold">Component probe</h1>
      <p className="mb-8 text-sm opacity-60">
        Resolved through <code>useDS()</code> — one file, any sandbox.
      </p>

      <Section title="Button">
        <Button variant="default">Primary</Button>
        <Button variant="secondary">Secondary</Button>
        <Button variant="outline">Outline</Button>
        <Button variant="ghost">Ghost</Button>
        <Button variant="danger">Danger</Button>
        <Button variant="default" disabled>
          Disabled
        </Button>
      </Section>

      <Section title="Badge">
        <Badge color="neutral">Neutral</Badge>
        <Badge color="blue">Blue</Badge>
        <Badge color="green">Paid</Badge>
        <Badge color="amber">Pending</Badge>
        <Badge color="red">Invalid color</Badge>
        <Badge color="danger">Failed</Badge>
      </Section>

      <Section title="Tag">
        <Tag>status is paid</Tag>
        <Tag>amount &gt; 500</Tag>
      </Section>

      <Section title="Input">
        <div className="w-64">
          <Input placeholder="Search orders" />
        </div>
      </Section>

      <Section title="Feedback">
        <Spinner />
        <Kbd>⌘K</Kbd>
      </Section>

      <Section title="Direction">
        <p className="max-w-prose text-sm">
          Latin text alongside Arabic: محمد عبد الرحمن — a dense table has to hold both.
        </p>
      </Section>
    </main>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-7">
      <h2 className="mb-3 text-xs font-semibold tracking-wide uppercase opacity-50">{title}</h2>
      <div className="flex flex-wrap items-center gap-3">{children}</div>
    </section>
  )
}
